apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sample
  labels:
    name: client-sample
  namespace: client-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      name: client-sample
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: client-sample
    spec:
      containers:
      - image: registry.digitalocean.com/logicwind/digitalocean-docker-registry-workflow:latest
        name: sample-app
        env:
          - name: CHARACTER
            value: "la app sample."
          - name: SLEEP_TIME
            value: "3"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-logicwind
